# Use the official Bun image as the base image
FROM oven/bun:latest

# Set the working directory
WORKDIR /app

# Copy package.json and bun.lockb files
COPY package.json bun.lockb ./
COPY packages/api/package.json ./packages/api/
COPY packages/frontend/package.json ./packages/frontend/

# Install dependencies
RUN bun install --filter "api" --frozen-lockfile

# Copy the rest of the application code
COPY ./ ./

# Expose the port the app runs on
EXPOSE 3000
