services:
  frontend:
    build:
      context: ./
      dockerfile: docker/frontend/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/stimmi
    volumes:
      - ./:/app
      - "/app/node_modules"
      - "/app/packages/frontend/node_modules"
    working_dir: /app
    command: bun --filter 'frontend' dev
    depends_on:
      - api
      - db
  api:
    build:
      context: ./
      dockerfile: docker/api/Dockerfile.dev
    ports:
      - "3001:3001"
      - "4983:4983"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/stimmi
    volumes:
      - ./:/app
      - "/app/node_modules"
      - "/app/packages/api/node_modules"
    working_dir: /app
    command: bun --filter 'api' dev
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stimmi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
