# Use the official Bun image as the base image
FROM oven/bun:latest

# Set the working directory
WORKDIR /app

# Copy package.json and bun.lockb files
COPY package.json bun.lockb ./
COPY packages/frontend/package.json ./packages/frontend/package.json

# Install dependencies
RUN bun install

# Copy the rest of the application code
COPY ./ ./

# Expose the port the app runs on
EXPOSE 3000
